name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-code:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pip install poetry
      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install --yes graphviz graphviz-dev
      - name: Install dependencies
        run: poetry install --no-root
      - name: Check code syntax
        run: poetry run flake8 --extend-ignore E501 .
      - name: Check code format
        run: poetry run black --diff .
      # - name: Perform unit test
      #   run: poetry run pytest tests.py
